# Generated by Django 4.1.7 on 2023-02-19 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoriesmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='imagesmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='pics')),
                ('ctname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Page_Reg.categoriesmodel')),
            ],
        ),
    ]
